version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(pathname)s %(lineno)s %(funcName)s %(message)s %(extra)s %(exc_info)s"

handlers:
  json_stream_handler:
    level: DEBUG
    class: logging.StreamHandler
    formatter: json

loggers:
  "":
    level: INFO
    handlers: [json_stream_handler]
    propogate: true

  "CQRSBus":
    level: DEBUG
    handlers: [json_stream_handler]
    propogate: true
