version: "3.9"

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: python deploy/uvicorn/uvicorn_run.py
    image: web_app_prod
    container_name: web_app_prod
    ports:
      - 80:80
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=${DB_NAME}
      - DB_USER_LOGIN=${DB_USER_LOGIN}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - USER_IDENTITY_SERVICE_SECRET=${USER_IDENTITY_SERVICE_SECRET}
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:14
    container_name: postgres_db_prod
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_LOGIN}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_db_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 3s
      retries: 30

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    build:
      context: deploy/prometheus/
      dockerfile: Dockerfile
    image: myeshop/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    container_name: grafana_container
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_db_data_prod:
  prometheus_data:
  grafana_data:
