version: "3.9"

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: uvicorn eshop.settings:MAIN_APP --host 0.0.0.0 --port 80 --reload
    # FOR debugging container
    # command: sleep infinity
    image: web_app_dev
    container_name: web_app_dev
    ports:
      - 80:80
    volumes:
      - ./:/usr/code/myeshop
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=${DB_NAME}
      - DB_USER_LOGIN=${DB_USER_LOGIN}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - USER_IDENTITY_SERVICE_SECRET=${USER_IDENTITY_SERVICE_SECRET}
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:14
    container_name: postgres_db_dev
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_LOGIN}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_db_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres_db_data_dev:
