version: "3.9"

services:
  web_app:
    build:
      context: .
      target: build_for_prod
    image: rwwwrl/myeshop_web_app:local_prod
    container_name: web_app

  nginx:
    build:
      context: deploy/nginx
    image: rwwwrl/myeshop_nginx:local_prod
    container_name: nginx

  prometheus:
    build:
      context: deploy/prometheus
    image: rwwwrl/myeshop_prometheus:local_prod

  grafana:
    build:
      context: deploy/grafana
    image: rwwwrl/myeshop_grafana:local_prod
