version: "3.9"

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: uvicorn eshop.settings:MAIN_APP --host 0.0.0.0 --port 80 --reload
    # FOR debugging container
    # command: sleep infinity
    image: rwwwrl/myeshop_web_app:dev
    container_name: myeshop_web_app_dev
    ports:
      - 80:80
    volumes:
      - ./eshop/:/usr/code/myeshop/eshop/
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER_LOGIN=${POSTGRES_DB_USER_LOGIN}
      - DB_USER_PASSWORD=${POSTGRES_DB_USER_PASSWORD}
      - USER_IDENTITY_SERVICE_SECRET=${USER_IDENTITY_SERVICE_SECRET}
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:14
    container_name: postgres_db_dev
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_DB_USER_PASSWORD}
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER_LOGIN}" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres_db_data:
