version: "3.9"

services:
  app:
    build:
      context: .
      target: build_for_run_pytest
    image: app_build_for_run_pytest
    command: pytest -c pytest.ini
    volumes:
      - ./eshop/:/usr/code/myeshop/eshop/
