version: "3.9"

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: uvicorn eshop.settings:MAIN_APP --host 0.0.0.0 --port 80 --reload
    # FOR debugging container
    # command: sleep infinity
    image: rwwwrl/myeshop_web_app:dev
    container_name: web_app
    ports:
      - 80:80
    volumes:
      - ./eshop/:/usr/code/myeshop/eshop/
    environment:
      - POSTGRES__HOST=postgres_db
      - POSTGRES__PORT=${POSTGRES__PORT}
      - POSTGRES__NAME=${POSTGRES__NAME}
      - POSTGRES__LOGIN=${POSTGRES__LOGIN}
      - POSTGRES__PASSWORD=${POSTGRES__PASSWORD}
      - USER_IDENTITY_SERVICE__SECRET=${USER_IDENTITY_SERVICE__SECRET}
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES__NAME}
      - POSTGRES_USER=${POSTGRES__LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES__LOGIN}" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres_db_data:
