version: "3.9"

services:
  web_app:
    image: rwwwrl/myeshop_web_app:main_latest

  nginx:
    image: rwwwrl/myeshop_nginx:main_latest
    volumes:
      - ssl_certificates_certbot_letsencrypt:/etc/letsencrypt
      - ssl_certificates_certbot_www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
      - 3000:3000

  loki_read:
    image: rwwwrl/myeshop_loki:main_latest

  loki_write:
    image: rwwwrl/myeshop_loki:main_latest

  minio:
    image: rwwwrl/myeshop_minio:main_latest

  promtail:
    image: rwwwrl/myeshop_promtail:main_latest

  prometheus:
    image: rwwwrl/myeshop_prometheus:main_latest

  postgres_db:
    ports:
      - 15432:5432

  grafana:
    image: rwwwrl/myeshop_grafana:main_latest

volumes:
  ssl_certificates_certbot_letsencrypt:
    external: true

  ssl_certificates_certbot_www:
    external: true
