"""create table author

Revision ID: 4b7c1c11401f
Revises: 24ef520486e4
Create Date: 2024-03-04 13:10:03.607122

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4b7c1c11401f'
down_revision: Union[str, None] = '24ef520486e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'test_app__author',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('test_app__book', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'test_app__book', 'test_app__author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_app__book', type_='foreignkey')
    op.drop_column('test_app__book', 'author_id')
    op.drop_table('test_app__author')
    # ### end Alembic commands ###
