"""UserIdentityService: create table User

Revision ID: 63c2af46fb49
Revises: 4b7c1c11401f
Create Date: 2024-03-12 08:53:47.048122

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '63c2af46fb49'
down_revision: Union[str, None] = '4b7c1c11401f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_identity__user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=40), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_identity__user_name'), 'user_identity__user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identity__user_name'), table_name='user_identity__user')
    op.drop_table('user_identity__user')
    # ### end Alembic commands ###
