"""initial

Revision ID: 7401a67498ee
Revises: 
Create Date: 2024-05-21 12:52:47.202428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7401a67498ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=40), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='user_identity'
    )
    op.create_index(op.f('ix_user_identity_user_name'), 'user', ['name'], unique=True, schema='user_identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identity_user_name'), table_name='user', schema='user_identity')
    op.drop_table('user', schema='user_identity')
    # ### end Alembic commands ###
