global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"

    scrape_interval: 5s

    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "postgres_db"

    scrape_interval: 5s

    static_configs:
      - targets: ["postgres_db_exporter:9187"]
