"""created basket_item; customer_basket tables

Revision ID: e129d01673b8
Revises: 
Create Date: 2024-06-04 12:04:49.798976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e129d01673b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customer_basket',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('buyer_id', sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='basket'
    )
    op.create_table(
        'basket_item',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('basket_id', sa.INTEGER(), nullable=False),
        sa.Column('product_id', sa.INTEGER(), nullable=False),
        sa.Column('product_name', sa.VARCHAR(length=50), nullable=False),
        sa.Column('unit_price', sa.DECIMAL(), nullable=False),
        sa.Column('quantity', sa.INTEGER(), nullable=False),
        sa.Column('picture_url', sa.VARCHAR(length=255), nullable=False),
        sa.CheckConstraint('quantity > 0', name='quantity_is_positive'),
        sa.CheckConstraint('unit_price > 0', name='unit_price_is_positive'),
        sa.ForeignKeyConstraint(
            ['basket_id'],
            ['basket.customer_basket.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='basket'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_item', schema='basket')
    op.drop_table('customer_basket', schema='basket')
    # ### end Alembic commands ###
