FROM python:3.11

RUN apt update
RUN mkdir -p /usr/code/myeshop

WORKDIR /usr/code/myeshop

EXPOSE 80

COPY . .

RUN pip install -e .

WORKDIR /usr/code/myeshop/eshop/

# for debugging container
ENTRYPOINT ["tail", "-f", "/dev/null"]
