version: "3.9"

services:
  web_app:
    build: .
    container_name: web_app
    ports:
      - 80:80
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_USER_PASSWORD}
      - POSTGRES_DB=myeshop
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres_db_data:
