FROM python:3.11

RUN apt update
RUN mkdir -p /usr/code/myeshop

WORKDIR /usr/code/myeshop

EXPOSE 80

COPY . .

RUN pip install -e .

WORKDIR /usr/code/myeshop/eshop/

CMD ["gunicorn", "eshop.wsgi", "-b", "0.0.0.0:80"]
