positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_write:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: scrape logs from docker containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
